apiVersion: v1
kind: PersistentVolume
metadata:
  name: ruoyi-demo-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/ruoyi-demo/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ruoyi-demo-mysql-pv-claim
  namespace: ruoyi-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    prod: mysql
  namespace: ruoyi-demo
spec:
  ports:
    - port: 3306
  selector:
    prod: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-mysql
  namespace: ruoyi-demo
  labels:
    prod: mysql
spec:
  selector:
    matchLabels:
      prod: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        prod: mysql
    spec:
      containers:
        - image: pubrepo.jiagouyun.com/demo/ruoyi-single-mysql:1.0
          name: ruoyi-mysql
          env:
            # 在实际中使用 secret
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: ruoyi-mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ruoyi-demo-mysql-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-redis
  labels:
    prod: redis
  namespace: ruoyi-demo
spec:
  selector:
    matchLabels:
      prod: redis
  replicas: 1
  template:
    metadata:
      labels:
        prod: redis
    spec:
      containers:
        - name: ruoyi-redis
          ports:
            - containerPort: 6379
          image: pubrepo.jiagouyun.com/demo/ruoyi-single-redis:1.0
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ruoyi-demo
  labels:
    prod: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379     # 容器端口
  selector:
    prod: redis
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-admin
  namespace: ruoyi-demo
  labels:
    app: ruoyi-admin
spec:
  selector:
    app: ruoyi-admin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-admin
  namespace: ruoyi-demo
  labels:
    app: ruoyi-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-admin
  template:
    metadata:
      labels:
        app: ruoyi-admin
      annotations:
        datakit/ruoyi-admin.logs: |
          [
            {
              "disable": false,
              "type": "file",
              "path":"/home/ruoyi/logs/*.log",
              "source":  "ruoyi-admin",
              "tags" : {
                "env": "prod"
              }
            }
          ]
    spec:
      containers:
        - name: ruoyi-admin 
          image: pubrepo.jiagouyun.com/demo/ruoyi-single-admin:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: admin-log
              mountPath: /home/ruoyi/logs

      restartPolicy: Always
      volumes:
        - name: admin-log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-web
  namespace: ruoyi-demo
  labels:
    app: ruoyi-web
spec:
  selector:
    app: ruoyi-web
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-web
  namespace: ruoyi-demo
  labels:
    app: ruoyi-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-web
  template:
    metadata:
      labels:
        app: ruoyi-web
      annotations:
        datakit/logs: |
          [
            {
              "disable": false,
              "source": "ruoyi-nginx",
              "service": "ruoyi-web"
            }
          ]
    spec:
      containers:
        - env:
            - name: CLIENT_TOKEN
              value: <YOUR-WORKSPACE-CLIENT-TOKEn>
          name: ruoyi-web
          image: pubrepo.jiagouyun.com/demo/ruoyi-single-web:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP

